BEGIN:VCARD
VERSION:3.0
N:Oleta Powers
FN:Oleta Powers
ORG:Robbins Firm
URL:https://www.robbinsfirm.com
TITLE:Staff
TEL;TYPE=WORK,VOICE:404-856-3251
TEL;TYPE=FAX,WORK:
PHOTO;ENCODING=b;VALUE=URI:
EMAIL;TYPE=PREF,INTERNET:opowers@robbinsfirm.com
END:VCARD